[package]
name = "ezmid"
version = "0.0.0"
authors = ["carrotflakes <carrotflakes@gmail.com>"]
edition = "2018"

[dependencies]
midly = { version = "0.5", default-features = false, features = ["alloc"] }

[dev-dependencies]
rodio = { version = "0.17", default-features = false }
